# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antidot < Formula
  desc "Cleans up your $HOME from those pesky dotfiles"
  homepage "https://github.com/doron-cohen/antidot"
  version "0.6.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/doron-cohen/antidot/releases/download/v0.6.2/antidot_0.6.2_Darwin_x86_64.tar.gz"
    sha256 "bef0ed69fa1565b8b943a51cbe90be74d71497798fff56049c8ea66eb909e8da"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/doron-cohen/antidot/releases/download/v0.6.2/antidot_0.6.2_Linux_x86_64.tar.gz"
    sha256 "3027e8a1f79741c5b644cf00e52aa232864ca76a8f813337eab343bc123605ed"
  end

  def install
    bin.install "antidot"
  end
end
